language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install setuptools==68.0.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install wheel==0.42.0; fi
  - pip install .
script:
  - python -m unittest discover
